//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalNeolaser.EF_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class neolaserdbEntities : DbContext
    {
        public neolaserdbEntities()
            : base("name=neolaserdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tAuditoria> tAuditorias { get; set; }
        public DbSet<tCliente> tClientes { get; set; }
        public DbSet<tItemsAuditado> tItemsAuditados { get; set; }
        public DbSet<tSubItem> tSubItems { get; set; }
        public DbSet<tSucursale> tSucursales { get; set; }
        public DbSet<tSucursalItem> tSucursalItems { get; set; }
        public DbSet<tItem> tItems { get; set; }
        public DbSet<tRole> tRoles { get; set; }
        public DbSet<tUsuario> tUsuarios { get; set; }
    
        public virtual ObjectResult<spElementosAuditarBySucursal_Result> spElementosAuditarBySucursal(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spElementosAuditarBySucursal_Result>("spElementosAuditarBySucursal", idParameter);
        }
    }
}
