//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalNeolaser.EF_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAuditoria
    {
        public tAuditoria()
        {
            this.tItemsAuditados = new HashSet<tItemsAuditado>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> FkUsuario { get; set; }
        public Nullable<int> FkSucursal { get; set; }
    
        public virtual tSucursale tSucursale { get; set; }
        public virtual ICollection<tItemsAuditado> tItemsAuditados { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
