//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalNeolaser.EF_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tItemsAuditado
    {
        public int Id { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> FkAuditoria { get; set; }
        public Nullable<int> FkSubItem { get; set; }
    
        public virtual tAuditoria tAuditoria { get; set; }
        public virtual tSubItem tSubItem { get; set; }
    }
}
