//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalNeolaser.EF_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tItem
    {
        public tItem()
        {
            this.tSubItems = new HashSet<tSubItem>();
            this.tSucursalItems = new HashSet<tSucursalItem>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<tSubItem> tSubItems { get; set; }
        public virtual ICollection<tSucursalItem> tSucursalItems { get; set; }
    }
}
