//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalNeolaser.EF_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSubItem
    {
        public tSubItem()
        {
            this.tItemsAuditados = new HashSet<tItemsAuditado>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> FkItem { get; set; }
    
        public virtual ICollection<tItemsAuditado> tItemsAuditados { get; set; }
        public virtual tItem tItem { get; set; }
    }
}
