//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalNeolaser.EF_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSucursale
    {
        public tSucursale()
        {
            this.tAuditorias = new HashSet<tAuditoria>();
            this.tSucursalItems = new HashSet<tSucursalItem>();
        }
    
        public int Id { get; set; }
        public string CodSAP { get; set; }
        public string Descripcion { get; set; }
        public string Poblacion { get; set; }
        public string Provincia { get; set; }
        public string CodPostal { get; set; }
        public Nullable<int> FkCliente { get; set; }
    
        public virtual ICollection<tAuditoria> tAuditorias { get; set; }
        public virtual tCliente tCliente { get; set; }
        public virtual ICollection<tSucursalItem> tSucursalItems { get; set; }
    }
}
