//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalNeolaser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipio
    {
        public int id_municipio { get; set; }
        public short id_provincia { get; set; }
        public int cod_municipio { get; set; }
        public int DC { get; set; }
        public string nombre { get; set; }
    }
}
