//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalNeolaser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surcusales_Grupos
    {
        public int Id { get; set; }
        public Nullable<int> FkSucursal { get; set; }
        public Nullable<int> FkGrupo { get; set; }
    
        public virtual GruposElemento GruposElemento { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
